project:
  type: website

website:
  title: "Dirschbacher Data Lab"

  navbar:
    right:
      - icon: github
        href: "https://github.com/Svenja161"

lang: de   # Standardsprache

languages:
  de:
    href: /dirschbacher-data-lab/de/
    title: "Dirschbacher Data Lab"
    navbar:
      left:
        - href: de/index.qmd
          text: "Start"
        - href: de/projects.qmd
          text: "Projekte"
        - href: de/about.qmd
          text: "Ãœber mich"
      right:
        - text: English
          href: /dirschbacher-data-lab/en/

  en:
    href: /dirschbacher-data-lab/en/
    title: "Dirschbacher Data Lab"
    navbar:
      left:
        - href: en/index.qmd
          text: "Home"
        - href: en/projects.qmd
          text: "Projects"
        - href: en/about.qmd
          text: "About me"
      right:
        - text: Deutsch
          href: /dirschbacher-data-lab/de/

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
