project:
  type: website
  output-dir: docs

website:
  title: "Dirschbacher Data Lab"

  navbar:
    left:
      - href: de/index.qmd
        text: "Start"
      - href: de/projects.qmd
        text: "Projekte"
      - href: de/about.qmd
        text: "Ãœber mich"
    right:
      - text: "English"
        href: en/index.html
      - icon: github
        href: "https://github.com/Svenja161"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css