project:
  type: website
  output-dir: docs

website:
  title: "Dirschbacher Data Lab"
  navbar:
    right:
      - icon: github
        href: "https://github.com/Svenja161"

  # Multi-Language Setup
  languages:
    de:
      title: "Dirschbacher Data Lab"
      navbar:
        left:
          - href: index.de.qmd
            text: "Start"
          - href: projects.de.qmd
            text: "Projekte"
          - href: about.de.qmd
            text: "Ãœber mich"

    en:
      title: "Dirschbacher Data Lab"
      navbar:
        left:
          - href: index.en.qmd
            text: "Home"
          - href: projects.en.qmd
            text: "Projects"
          - href: about.en.qmd
            text: "About me"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css