project:
  type: website
  output-dir: docs

website:
  title: "Dirschbacher Data Lab"

  navbar:
    right:
      - icon: github
        href: "https://github.com/Svenja161"

lang: de

languages:
  de:
    href: de/
    title: "Dirschbacher Data Lab"
    navbar:
      left:
        - href: de/index.qmd
          text: "Start"
        - href: de/projects.qmd
          text: "Projekte"
        - href: de/about.qmd
          text: "Ãœber mich"
      right:
        - text: English
          href: ../en/index.html

  en:
    href: en/
    title: "Dirschbacher Data Lab"
    navbar:
      left:
        - href: en/index.qmd
          text: "Home"
        - href: en/projects.qmd
          text: "Projects"
        - href: en/about.qmd
          text: "About me"
      right:
        - text: Deutsch
          href: ../de/index.html

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css