project:
  type: website

website:
  title: "Dirschbacher Data Lab"
  navbar:
    left:
      - text: Deutsch
        href: de/index.qmd
      - text: English
        href: en/index.qmd
    right:
      - icon: github
        href: "https://github.com/Svenja161"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
