project:
  output-dir: docs/de

website:
  title: "Dirschbacher Data Lab"
  navbar:
    left:
      - href: index.qmd
        text: "Start"
      - href: projects.qmd
        text: "Projekte"
      - href: about.qmd
        text: "Ãœber mich"

    right:
      - text: "English"
        href: ../en/index.html
      - icon: github
        href: "https://github.com/Svenja161"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

lang: de
