project:
  type: website
  output-dir: docs

website:
  title: "Dirschbacher Data Lab"
  navbar:
    left:
      - href: index.qmd
        text: "Start"
      - href: index.de.qmd
        text: "Deutsch"
      - href: index.en.qmd
        text: "English"
      - href: projects.de.qmd
        text: "Projekte"
      - href: projects.en.qmd
        text: "Projects"
      - href: about.de.qmd
        text: "Ãœber mich"
      - href: about.en.qmd
        text: "About me"
    right:
      - icon: github
        href: "https://github.com/Svenja161"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
